<?php
/**
 *
 * @author    hemengqiang
 * @version   1.0
 * @since     2017/9/6 上午10:06
 */
namespace app\api\controller\v1;

use app\common\controller\Api;

class Index extends Api
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        echo 222;
    }
}
