<?php
/**
 * Elasticsearch Demo
 * @author    hemengqiang
 * @version   1.0
 * @since     2017/9/5 上午9:52
 */
namespace app\api\controller\v1;

use app\common\controller\Api;
use Elasticsearch\ClientBuilder;

class search extends Api
{

    private $elasticsearchClinet;

    //索引名称
    private $index = 'log';

    //索引类型名称
    private $indexType = 'run_log';

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->elasticsearchClinet = ClientBuilder::create()->build();
    }

    /**
     * 创建索引
     * @author    hemengqiang
     * @version   1.0
     * @return    void
     */
    public function createIndex()
    {
        $createParams = [
            'index' => $this->index,
            'body' => [
                'settings' => [
                    'number_of_shards' => 2,
                    'number_of_replicas' => 0
                ]
            ]
        ];

        $response = $this->elasticsearchClinet->indices()->create($createParams);
        dump($response);
    }

    /**
     * 删除索引
     * @author    hemengqiang
     * @version   1.0
     * @return    void
     */
    public function deleteIndex()
    {
        $deleteParams = [
            'index' => $this->index,
        ];
        $response = $this->elasticsearchClinet->indices()->delete($deleteParams);
        dump($response);
    }

    /**
     * 判断索引是否存在
     * @author    hemengqiang
     * @version   1.0
     * @return    void
     */
    public function existsIndex()
    {
        $existsParams = [
            'index' => $this->index,
        ];

        $response = $this->elasticsearchClinet->indices()->exists($existsParams);
        dump($response);

    }

    /**
     * 增加索引数据
     * @author    hemengqiang
     * @version   1.0
     * @return    void
     */
    public function indexDoument()
    {
        $params = [
            'index' => $this->index,
            'type' => $this->indexType,
            'id' => '39',
            'body' => [
                'title' => '酷派暮年：郭德英、贾跃亭、刘江峰都走了，为何谁都没能拯救它？',
                'desc' => '周杰伦酷派暮年：郭德英、贾跃亭、刘江峰都走了，为何谁都没能拯救它？'
            ]
        ];

        $response = $this->elasticsearchClinet->index($params);
        dump($response);
    }

    /**
     * 获得数据
     * @author    hemengqiang
     * @version   1.0
     * @return    void
     */
    public function getDoument()
    {
        $getParams = [
            'index' => $this->index,
            'type' => $this->indexType,
            'id' => '35'
        ];

        $response = $this->elasticsearchClinet->get($getParams);
        dump($response);
    }

    /**
     * 搜索
     * @author    hemengqiang
     * @version   1.0
     * @return    void
     */
    public function searchDoument()
    {
        $searchParams = [
            'index' => $this->index,
            'type' => $this->indexType,
            'body' => [
                'query' => [
                    'match' => [
                        'title' => '何',
                    ],
                    'match' => [
                        'desc' => '何',
                    ],
                ]
            ],
            'size' => 2,
            'from' => 0
         ];

        $response = $this->elasticsearchClinet->search($searchParams);
        dump($response);
    }

}